#!/bin/bash

# packages
sudo apt install \
	xorg \
	libx11-dev \
	xserver-xorg-dev \
	xorg-dev \
	libxext-dev \
	libxcb1-dev \
	libxcb-damage0-dev \
	libxcb-dpms0-dev \
	libxcb-xfixes0-dev \
	libxcb-shape0-dev \
	libxcb-render-util0-dev \
	libxcb-render0-dev \
	libxcb-randr0-dev \
	libxcb-composite0-dev \
	libxcb-image0-dev \
	libxcb-present-dev \
	libxcb-glx0-dev \
	libxcb-util0-dev \
	libpixman-1-dev \
	libdbus-1-dev \
	libconfig-dev \
	libgl-dev \
	libegl-dev \
	libpcre2-dev \
	libevdev-dev \
	uthash-dev \
	libev-dev \
	libx11-xcb-dev \
	mesa-utils \
	libgl1-mesa-glx \
	libgl1-mesa-dev \
	meson \
	feh \
	lsd \
	sxhkd \
    stow \
