#!/bin/sh

# XDG variables
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local"
export XDG_CACHE_HOME="$HOME/.cache"

# Default Programs
export VISUAL="nvim"
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="brave"
export PDFVIEWER="zathura"
export FILE_EXPLORER="thunar"

# program config locations
export GOPATH="$HOME/.go"
export COMPOSER_HOME="$HOME/.composer"

# PATH Environment Variable
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$XDG_DATA_HOME/bin"
export PATH="$PATH:$HOME/.composer/vendor/bin"
export PATH="$PATH:$HOME/.cargo/bin"
