#!/bin/bash

# XDG variables
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local"
export XDG_CACHE_HOME="$HOME/.cache"

# Default Programs
export EDITOR="nvim"
export TERMINAL="alacritty"
export TERMINAL_ARGS="-e tmux"
export BROWSER="chromium"
export PDFVIEWER="zathura"
export FILE_EXPLORER="nautilus"

# program config locations
export VIMRC="$XDG_CONFIG_HOME/nvim/init.lua"
export VIMCONFDIR="$XDG_CONFIG_HOME/nvim"
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"
export GOPATH="$HOME/.go"
export COMPOSER_HOME="$HOME/.composer"
export PERL5LIB="$HOME/.perl5/lib/perl5"
export MANPATH="$MANPATH:$HOME/.perl5/man"

# PATH Environment Variable
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$XDG_DATA_HOME/bin"
export PATH="$PATH:$HOME/.composer/vendor/bin"
export PATH="$PATH:$(ruby -e 'puts Gem.user_dir')/bin"
export PATH="$PATH:$HOME/.perl5/bin"
export PATH="$PATH:$XDG_DATA_HOME/JetBrains/Toolbox/scripts"
export PATH="$PATH:$HOME/.cargo/bin"

# Misc
export CHROME_EXECUTABLE="/usr/bin/google-chrome-stable"
