#!/bin/bash

# Session environment variables
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local"
export XDG_CACHE_HOME="$HOME/.cache"

export CHROME_EXECUTABLE="/usr/bin/google-chrome-stable"
export GOPATH="$HOME/.go"
export COMPOSER_HOME="$HOME/.composer"
export ANDROID_HOME="/opt/android-sdk"
export PERL5LIB="$HOME/.perl5/lib/perl5"
export PATH="$PATH:$GOPATH/bin:$HOME/.local/bin:$HOME/.composer/vendor/bin:$(ruby -e 'puts Gem.user_dir')/bin:$HOME/.perl5/bin:$XDG_DATA_HOME/JetBrains/Toolbox/scripts:$HOME/.cargo/bin:$HOME/.dev/flutter/bin"
export MANPATH="$MANPATH:$HOME/.perl5/man"

export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"
